### ISSUE TITLE
Force-syncing a collection does not always lead to a remote settings sync event

### ISSUE THREAD

**Issue by motin** [mozilla/messaging-system-personalization-experiment-1-addon#10]
After leaving the add-on running for a couple of hours I noticed this behavior. Have only happened once, but when it happened there was no sync events being triggered at all until a browser restart. 

The fact that this happened makes me think that we might not always get newly computed scores in some cases (since they only get computed on remote settings sync events) if we rely on [the current sync mechanism](https://github.com/mozilla/messaging-system-personalization-experiment-1-addon/blob/0f4cc54fcfa36e5e714d858d28c1deedf6ca5d43/src/privileged/remoteSettings/api.js#L48-L51).

**Comment by motin** [comment]
An alternative is to query the collection endpoints directly. @crankycoder, what do you think about that approach?

**Comment by crankycoder** [comment]
👍 I would just query the remote setting endpoint directly.  RemoteSettings is fronted by CDNs so I wouldn't expect a problem.

**Comment by motin** [comment]
Fixed in https://github.com/mozilla/messaging-system-personalization-experiment-1-addon/commit/874a6e7cbfca826ba3ef6efbfb06912d52187ffe
