### ISSUE TITLE
Handle the case when total_uri_count is undefined

### ISSUE THREAD

**Issue by motin** [mozilla/messaging-system-personalization-experiment-1-addon#21]
Affected version: 1.0.0

I noticed (in a long-running session) that the study had ended due to a failed telemetry validation. It turned out that total_uri_count had returned undefined for some reason. 

This needs to be handled in the add-on. Could be by ensuring that total_uri_count is never returned undefined, or allowing undefined values, or removing the feature, for instance. Without handling this case, any such unexpected occurance will lead to study unenrollment.

**Comment by motin** [comment]
Gist with the entire add-on console output exported: https://gist.github.com/motin/55a5b65160b37e8eace0e35d59072bed

**Comment by crankycoder** [comment]
Fixed in https://github.com/mozilla/messaging-system-personalization-experiment-1-addon/pull/24
