### ISSUE TITLE
Add model verification to WebExtension based on model schema

### ISSUE THREAD

**Issue by mlopatka** [mozilla/messaging-system-personalization-experiment-1-addon#3]
Please implement the following verification checkpioint that check model integrity when completing a sync event.

- model weights must be integer values
- default threshold for a CFR to be shown is 5000
- model weights must all fall within the range 0-10000
- model weight values must not all be equal or all be 0

**Comment by mlopatka** [comment]
@motin ^

**Comment by motin** [comment]
Implemented all validations except for the last one. Due to integer rounding amongst other reasons, there is no guarantee that the scores are not all equal or all 0, and I chose not to throw any error if/when that happens, since errors thrown leads to study unenrollment.
