### ISSUE TITLE
Implement hourly model sync event mediated by WebExtension

### ISSUE THREAD

**Issue by mlopatka** [mozilla/messaging-system-personalization-experiment-1-addon#6]
Decision was reached to aim for an hourly model update cadence.
Please implement hourly sync events initiated by the addon.

**Comment by motin** [comment]
Do these need to be in sync with other clients, eg always update on the hour (X:00), or just "at least once every hour" on each client individually? I will assume the former since we used a similar setup in the FLv2 study.

**Comment by mlopatka** [comment]
We want to have a soft guarantee that the clients are on the most recent model version compared to their most recent active session. Having updates triggered on X:00 hour can help us with scheduling the model update ETL job accordingly. 

The downside is if a client is only active between X:12 and X:48 for example, they will not get an update. So the "at least once every hour" option is a better fit to ensure current model versions get maximum coverage of the active client set at any given time.

**Comment by crankycoder** [comment]
Can we use the `runtime.onStartup` API as well as a timer to make sure the model is at most 60 minutes old?

**Comment by motin** [comment]
I chose to use browser.alarms: https://github.com/mozilla/messaging-system-personalization-experiment-1-addon/pull/2/commits/91c60e7e32c608a55100908c2dbddbe392f079f2#diff-961641dd6af66f5e3313307cf4eb8f1dR90-R106
