### ISSUE TITLE
Use native fs Promises API?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/messaging-system-personalization-experiment-1-addon#8]
https://github.com/mozilla/messaging-system-personalization-experiment-1-addon/blob/9cdbe868eec9fe69a11efcba561ebc07fa21f1e2/build.js#L14-L19

I haven't played with it much, but I believe that Node already has a promisified version of the `fs` API: https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api

```js
const fs = require("fs").promises;

main();

async function main() {
  const files = await fs.readdir("./foo");
  console.log(files);

  try {
    // promisified rimraf.
    await fs.rmdir("./foo/bar", { recursive: true });
    console.log("removed");
  } catch (err) {
    console.error(err);
  }
}
```

**Comment by motin** [comment]
Thanks @pdehaan, would you mind filing this against the upstream https://github.com/mozilla/normandy-nextgen-study-example repo instead? Thanks :)
